task:
  name: Confirm Coffee Preferences
  element:
    input:
      - order
    output:
      - order
      - items
  dataobject:
    write:
      - a1
    read
      - a4
      - a7

task:
  name: Get Sun Data
  element:
    input:
      - date
    output:
      - sunrise
      - sunset
  dataobject:
    write: tasks for hour (data element is written by these):
      - a2
    read:
      - a5
      - a6


